// frontend/src/views/AuthPage.vue
<script setup>
import { ref, computed, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/authStore'

const router = useRouter()
const authStore = useAuthStore()

const activeTab = ref('login')
const username = ref('')
const password = ref('')
const confirmPassword = ref('')
const errors = ref({})
const showPassword = ref(false)
const showConfirmPassword = ref(false)

const isLogin = computed(() => activeTab.value === 'login')
const isLoading = computed(() => authStore.isLoading)

watch(activeTab, () => {
  errors.value = {}
  showPassword.value = false
  showConfirmPassword.value = false
})

function validateForm() {
  errors.value = {}
  
  if (!username.value.trim()) {
    errors.value.username = '请输入用户名'
  } else if (username.value.length < 4 || username.value.length > 16) {
    errors.value.username = '用户名长度为4-16位'
  }
  
  if (!password.value) {
    errors.value.password = '请输入密码'
  } else if (password.value.length < 6) {
    errors.value.password = '密码长度至少6位'
  }
  
  if (!isLogin.value && password.value !== confirmPassword.value) {
    errors.value.confirmPassword = '两次输入的密码不一致'
  }
  
  return Object.keys(errors.value).length === 0
}

async function handleSubmit() {
  if (!validateForm()) return
  
  let success = false
  
  if (isLogin.value) {
    success = await authStore.login(username.value.trim(), password.value)
    if (success) {
      router.push('/upload')
    }
  } else {
    success = await authStore.register(username.value.trim(), password.value)
    if (success) {
      // 注册成功后自动登录
      const loginSuccess = await authStore.login(username.value.trim(), password.value)
      if (loginSuccess) {
        router.push('/upload')
      }
    }
  }
}

function handleGuestMode() {
  localStorage.setItem('feynman_guest', 'true')
  router.push('/select')
}
</script>

<template>
  <div class="auth-page">
    <div class="auth-logo-btn" @click="router.push('/select')">费曼伴学</div>
    <div class="auth-container">
      <div class="auth-header">
        <h1 class="auth-title">费曼伴学</h1>
        <p class="auth-subtitle">登录你的学习账号，保存教材与讲解记录</p>
      </div>

      <div class="auth-tabs">
        <div class="tab-indicator" :style="{ transform: isLogin ? 'translateX(0%)' : 'translateX(100%)' }"></div>
        <button
          class="tab-btn"
          :class="{ 'tab-btn--active': isLogin }"
          @click="activeTab = 'login'"
        >
          登录
        </button>
        <button
          class="tab-btn"
          :class="{ 'tab-btn--active': !isLogin }"
          @click="activeTab = 'register'"
        >
          注册
        </button>
      </div>

      <form class="auth-form" @submit.prevent="handleSubmit">
        <div class="form-group">
          <div class="input-wrapper" :class="{ 'input-wrapper--error': errors.username }">
            <input
              v-model="username"
              type="text"
              class="form-input"
              placeholder="请输入用户名（4-16位字母/数字）"
              :disabled="isLoading"
              autocomplete="username"
            />
          </div>
          <p v-if="errors.username" class="error-message">{{ errors.username }}</p>
        </div>

        <div class="form-group">
          <div class="input-wrapper" :class="{ 'input-wrapper--error': errors.password }">
            <input
              v-model="password"
              :type="showPassword ? 'text' : 'password'"
              class="form-input"
              placeholder="请输入密码（最少6位）"
              :disabled="isLoading"
              autocomplete="current-password"
            />
            <button
              type="button"
              class="eye-toggle"
              @click="showPassword = !showPassword"
              :disabled="isLoading"
            >
              <svg v-if="showPassword" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
                <path d="M9.87 9.87a3 3 0 1 0 4.24 4.24" />
                <path d="M10.73 5.08A10.43 10.43 0 0 1 12 5c7 0 10 7 10 7a13.16 13.16 0 0 1-1.67 2.68" />
                <path d="M6.61 6.61A13.526 13.526 0 0 0 2 12s3 7 10 7c1.49 0 2.93-.26 4.24-.73" />
                <line x1="2" y1="2" x2="22" y2="22" />
              </svg>
              <svg v-else width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
                <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7z" />
                <circle cx="12" cy="12" r="3" />
              </svg>
            </button>
          </div>
          <p v-if="errors.password" class="error-message">{{ errors.password }}</p>
        </div>

        <div v-if="!isLogin" class="form-group">
          <div class="input-wrapper" :class="{ 'input-wrapper--error': errors.confirmPassword }">
            <input
              v-model="confirmPassword"
              :type="showConfirmPassword ? 'text' : 'password'"
              class="form-input"
              placeholder="再次输入密码"
              :disabled="isLoading"
              autocomplete="new-password"
            />
            <button
              type="button"
              class="eye-toggle"
              @click="showConfirmPassword = !showConfirmPassword"
              :disabled="isLoading"
            >
              <svg v-if="showConfirmPassword" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
                <path d="M9.87 9.87a3 3 0 1 0 4.24 4.24" />
                <path d="M10.73 5.08A10.43 10.43 0 0 1 12 5c7 0 10 7 10 7a13.16 13.16 0 0 1-1.67 2.68" />
                <path d="M6.61 6.61A13.526 13.526 0 0 0 2 12s3 7 10 7c1.49 0 2.93-.26 4.24-.73" />
                <line x1="2" y1="2" x2="22" y2="22" />
              </svg>
              <svg v-else width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
                <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7z" />
                <circle cx="12" cy="12" r="3" />
              </svg>
            </button>
          </div>
          <p v-if="errors.confirmPassword" class="error-message">{{ errors.confirmPassword }}</p>
        </div>

        <p v-if="authStore.errorMsg" class="form-error">{{ authStore.errorMsg }}</p>

        <button
          type="submit"
          class="submit-btn"
          :disabled="isLoading"
        >
          <svg v-if="isLoading" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="spinner">
            <circle cx="12" cy="12" r="10" stroke-linecap="round" stroke-dasharray="16 16" />
          </svg>
          <span>{{ isLoading ? (isLogin ? '登录中' : '注册中') : (isLogin ? '登录' : '注册') }}</span>
        </button>

        <p class="auth-link">
          {{ isLogin ? '还没有账号？' : '已有账号？' }}
          <button type="button" class="link-btn" @click="activeTab = isLogin ? 'register' : 'login'">
            {{ isLogin ? '去注册' : '去登录' }}
          </button>
        </p>

      </form>

      <div class="guest-section">
        <div class="divider">
          <span>或</span>
        </div>
        <button class="guest-btn" @click="handleGuestMode">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
            <polyline points="14 2 14 8 20 8" />
            <line x1="16" y1="13" x2="8" y2="13" />
            <line x1="16" y1="17" x2="8" y2="17" />
            <polyline points="10 9 9 9 8 9" />
          </svg>
          <span>游客模式体验</span>
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.auth-page {
  min-height: 100vh;
  background: linear-gradient(160deg, #f8f9fc 0%, #eef1f7 100%);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 64px 16px;
  font-family: 'Noto Sans SC', 'Inter', sans-serif;
}

.auth-logo-btn {
  position: fixed;
  top: 0;
  left: 0;
  padding: 0 24px;
  height: 56px;
  display: flex;
  align-items: center;
  font-size: 15px;
  font-weight: 600;
  color: #1E293B;
  cursor: pointer;
  z-index: 20;
  transition: color 150ms;
}

.auth-logo-btn:hover {
  color: #2563EB;
}

.auth-container {
  width: 100%;
  max-width: 420px;
  background: #FFFFFF;
  border-radius: 12px;
  padding: 40px 32px;
  box-shadow: 0 4px 32px rgba(0, 0, 0, 0.08), 0 1px 4px rgba(0, 0, 0, 0.04);
}

.auth-header {
  text-align: left;
  margin-bottom: 24px;
}

.auth-title {
  font-size: 24px;
  font-weight: 700;
  color: #1E293B;
  margin: 0 0 6px;
}

.auth-subtitle {
  font-size: 14px;
  color: #64748B;
  margin: 0;
}

.auth-tabs {
  position: relative;
  display: flex;
  border-bottom: 1px solid #E2E8F0;
  margin-bottom: 24px;
}

.tab-indicator {
  position: absolute;
  bottom: 0;
  left: 0;
  height: 2px;
  width: 50%;
  background: #2563EB;
  transition: transform 200ms ease-out;
}

.tab-btn {
  flex: 1;
  padding: 0 0 12px;
  border: none;
  background: transparent;
  font-size: 14px;
  font-weight: 600;
  color: #64748B;
  transition: color 150ms;
}

.tab-btn--active {
  color: #2563EB;
}

.auth-form {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.input-wrapper {
  display: flex;
  align-items: center;
  padding: 12px 16px;
  border-radius: 12px;
  border: 1px solid #E2E8F0;
  background: #FFFFFF;
  transition: all 150ms;
}

.input-wrapper:focus-within {
  border-color: #2563EB;
  box-shadow: 0 0 0 2px rgba(37, 99, 235, 0.2);
}

.input-wrapper--error {
  border-color: #F87171;
}

.input-wrapper--error:focus-within {
  box-shadow: 0 0 0 2px rgba(248, 113, 113, 0.2);
}

.form-input {
  flex: 1;
  border: none;
  outline: none;
  font-size: 15px;
  color: #1E293B;
  background: transparent;
}

.form-input::placeholder {
  color: #94A3B8;
}

.form-input:disabled {
  opacity: 0.6;
}

.eye-toggle {
  padding: 2px;
  border: none;
  background: transparent;
  color: #94A3B8;
  cursor: pointer;
  transition: color 150ms;
}

.eye-toggle:hover:not(:disabled) {
  color: #1E293B;
}

.eye-toggle:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.error-message {
  display: flex;
  align-items: center;
  gap: 6px;
  padding-left: 4px;
  font-size: 12px;
  color: #EF4444;
}

.form-error {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 14px;
  background: rgba(239, 68, 68, 0.08);
  border: 1px solid rgba(239, 68, 68, 0.2);
  border-radius: 12px;
  font-size: 14px;
  color: #DC2626;
}

.submit-btn {
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 12px;
  border: none;
  border-radius: 12px;
  font-size: 15px;
  font-weight: 600;
  background: #2563EB;
  color: #FFFFFF;
  box-shadow: 0 2px 8px rgba(37, 99, 235, 0.2);
  transition: all 150ms;
}

.submit-btn:hover:not(:disabled) {
  background: #1D4ED8;
}

.submit-btn:active:not(:disabled) {
  transform: scale(0.99);
}

.submit-btn:disabled {
  background: #CBD5E1;
  color: #94A3B8;
  cursor: not-allowed;
  box-shadow: none;
}

.auth-link {
  text-align: center;
  font-size: 13px;
  color: #64748B;
  margin: 4px 0 0;
}

.link-btn {
  border: none;
  background: transparent;
  color: #2563EB;
  font-weight: 500;
  cursor: pointer;
  text-decoration: underline;
  text-underline-offset: 4px;
  transition: color 150ms;
}

.link-btn:hover {
  color: #1D4ED8;
}

.spinner {
  animation: spin 1s linear infinite;
}

@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.guest-section {
  margin-top: 20px;
}

.divider {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 14px;
}

.divider::before,
.divider::after {
  content: '';
  flex: 1;
  height: 1px;
  background: #E2E8F0;
}

.divider span {
  font-size: 12px;
  color: #94A3B8;
}

.guest-btn {
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 12px;
  border: 1px solid #E2E8F0;
  border-radius: 12px;
  font-size: 14px;
  font-weight: 500;
  color: #64748B;
  background: #FFFFFF;
  transition: all 150ms;
}

.guest-btn:hover {
  background: #F8FAFC;
  border-color: #CBD5E1;
}

.guest-btn svg {
  color: #94A3B8;
}
</style>

// Design chat interface722/src/app/pages/AuthPage.tsx
import { useState, useEffect } from "react";
import { useNavigate } from "react-router";
import { Eye, EyeOff, Loader2, AlertCircle } from "lucide-react";
import { Toaster, toast } from "sonner";
import { saveAuth, isLoggedIn, mockLogin, mockRegister } from "../lib/auth";

/* ─── Types ─── */
type Tab = "login" | "register";

interface FieldError {
  username?: string;
  password?: string;
  confirm?: string;
}

/* ─── Validation ─── */
const USERNAME_RE = /^[a-zA-Z0-9]+$/;

function filterUsername(v: string) {
  return v.replace(/[^a-zA-Z0-9]/g, "");
}

function validateUsername(v: string): string | undefined {
  if (!v) return "用户名不能为空";
  if (!USERNAME_RE.test(v) || v.length < 4 || v.length > 16)
    return "用户名长度需 4–16 位，仅支持字母数字";
}

function validatePassword(v: string): string | undefined {
  if (!v) return "密码不能为空";
  if (v.length < 6) return "密码长度不能少于 6 位";
}

function validateConfirm(pw: string, confirm: string): string | undefined {
  if (!confirm) return "密码不能为空";
  if (pw !== confirm) return "两次输入的密码不一致";
}

/* ─── Input component ─── */
function FormInput({
  type,
  value,
  onChange,
  onBlur,
  placeholder,
  error,
  right,
  autoComplete,
}: {
  type: string;
  value: string;
  onChange: (v: string) => void;
  onBlur?: () => void;
  placeholder: string;
  error?: string;
  right?: React.ReactNode;
  autoComplete?: string;
}) {
  return (
    <div className="flex flex-col gap-1">
      <div
        className={`flex items-center rounded-xl border bg-background transition-all duration-150 ring-0
          ${error ? "border-red-400 focus-within:ring-2 focus-within:ring-red-200" : "border-border focus-within:border-primary focus-within:ring-2 focus-within:ring-ring"}`}
      >
        <input
          type={type}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          onBlur={onBlur}
          placeholder={placeholder}
          autoComplete={autoComplete}
          className="flex-1 px-4 py-3 text-[0.9375rem] text-foreground placeholder:text-muted-foreground bg-transparent outline-none rounded-xl"
        />
        {right && <div className="pr-3">{right}</div>}
      </div>
      {error && (
        <div className="flex items-center gap-1.5 px-1">
          <AlertCircle size={12} className="text-red-500 flex-shrink-0" strokeWidth={2} />
          <span className="text-[0.78rem] text-red-500 leading-none">{error}</span>
        </div>
      )}
    </div>
  );
}

/* ─── Eye toggle ─── */
function EyeToggle({ show, onToggle }: { show: boolean; onToggle: () => void }) {
  return (
    <button
      type="button"
      tabIndex={-1}
      onClick={onToggle}
      className="text-muted-foreground hover:text-foreground transition-colors p-0.5 focus-visible:outline-none"
      aria-label={show ? "隐藏密码" : "显示密码"}
    >
      {show ? <EyeOff size={17} strokeWidth={1.8} /> : <Eye size={17} strokeWidth={1.8} />}
    </button>
  );
}

/* ─── Main page ─── */
export default function AuthPage() {
  const navigate = useNavigate();
  const [tab, setTab] = useState<Tab>("login");

  // Login form state
  const [loginUsername, setLoginUsername] = useState("");
  const [loginPassword, setLoginPassword] = useState("");
  const [loginShowPw, setLoginShowPw] = useState(false);
  const [loginErrors, setLoginErrors] = useState<FieldError>({});
  const [loginApiError, setLoginApiError] = useState("");
  const [loginLoading, setLoginLoading] = useState(false);

  // Register form state
  const [regUsername, setRegUsername] = useState("");
  const [regPassword, setRegPassword] = useState("");
  const [regConfirm, setRegConfirm] = useState("");
  const [regShowPw, setRegShowPw] = useState(false);
  const [regShowConfirm, setRegShowConfirm] = useState(false);
  const [regErrors, setRegErrors] = useState<FieldError>({});
  const [regApiError, setRegApiError] = useState("");
  const [regLoading, setRegLoading] = useState(false);

  // Redirect if already logged in
  useEffect(() => {
    if (isLoggedIn()) navigate("/upload", { replace: true });
  }, []);

  /* ── Tab switch ── */
  function switchTab(t: Tab) {
    setTab(t);
    // clear all form state
    setLoginUsername(""); setLoginPassword(""); setLoginShowPw(false);
    setLoginErrors({}); setLoginApiError("");
    setRegUsername(""); setRegPassword(""); setRegConfirm("");
    setRegShowPw(false); setRegShowConfirm(false);
    setRegErrors({}); setRegApiError("");
  }

  /* ── Login ── */
  function loginCanSubmit() {
    return loginUsername.trim() !== "" && loginPassword !== "";
  }

  function validateLoginLocally(): FieldError {
    return {
      username: validateUsername(loginUsername),
      password: validatePassword(loginPassword),
    };
  }

  async function handleLogin() {
    if (loginLoading) return;
    const errs = validateLoginLocally();
    if (errs.username || errs.password) {
      setLoginErrors(errs);
      return;
    }
    setLoginErrors({});
    setLoginApiError("");
    setLoginLoading(true);
    try {
      const { token, userId } = await mockLogin(loginUsername, loginPassword);
      saveAuth(token, userId, loginUsername);
      toast.success("登录成功");
      navigate("/upload", { replace: true });
    } catch (e: unknown) {
      const err = e as { status?: number };
      if (err?.status === 401 || err?.status === 400) {
        setLoginApiError("用户名或密码错误");
      } else {
        toast.error("网络异常，请稍后重试");
      }
    } finally {
      setLoginLoading(false);
    }
  }

  /* ── Register ── */
  function regCanSubmit() {
    return regUsername !== "" && regPassword !== "" && regConfirm !== "" && regPassword === regConfirm;
  }

  function validateRegLocally(): FieldError {
    return {
      username: validateUsername(regUsername),
      password: validatePassword(regPassword),
      confirm: validateConfirm(regPassword, regConfirm),
    };
  }

  async function handleRegister() {
    if (regLoading) return;
    const errs = validateRegLocally();
    if (errs.username || errs.password || errs.confirm) {
      setRegErrors(errs);
      return;
    }
    setRegErrors({});
    setRegApiError("");
    setRegLoading(true);
    try {
      const { userId } = await mockRegister(regUsername);
      toast.success("注册成功，自动登录中…");
      // auto-login
      const { token } = await mockLogin(regUsername, regPassword).catch(() => ({
        token: `mock-token-${Date.now()}`,
      }));
      saveAuth(token as string, userId, regUsername);
      navigate("/upload", { replace: true });
    } catch (e: unknown) {
      const err = e as { status?: number };
      if (err?.status === 400) {
        setRegApiError("该用户名已被占用，请更换用户名");
      } else {
        toast.error("网络异常，请稍后重试");
      }
    } finally {
      setRegLoading(false);
    }
  }

  return (
    <div
      className="min-h-screen flex flex-col"
      style={{
        fontFamily: "'Noto Sans SC', 'Inter', sans-serif",
        background: "linear-gradient(160deg, #f8f9fc 0%, #eef1f7 100%)",
      }}
    >
      <Toaster position="top-center" richColors />

      {/* Top-left logo */}
      <div className="fixed top-0 left-0 px-6 h-14 flex items-center z-20">
        <button
          onClick={() => navigate("/upload")}
          className="text-[0.9375rem] font-semibold text-foreground hover:text-primary transition-colors"
        >
          费曼伴学
        </button>
      </div>

      {/* Centered card */}
      <div className="flex-1 flex items-center justify-center px-4 py-16">
        <div
          className="bg-white rounded-[12px] w-full"
          style={{
            maxWidth: 420,
            padding: "40px 32px",
            boxShadow: "0 4px 32px rgba(0,0,0,0.08), 0 1px 4px rgba(0,0,0,0.04)",
          }}
        >
          {/* Card header */}
          <div className="mb-6">
            <h1 className="text-[1.5rem] font-bold text-foreground leading-tight mb-1.5">费曼伴学</h1>
            <p className="text-[0.875rem] text-muted-foreground leading-relaxed">
              登录你的学习账号，保存教材与讲解记录
            </p>
          </div>

          {/* Tab bar */}
          <div className="relative flex border-b border-border mb-6">
            <div
              className="absolute bottom-0 left-0 h-[2px] w-1/2 bg-primary transition-transform duration-200 ease-out"
              style={{ transform: tab === "login" ? "translateX(0%)" : "translateX(100%)" }}
            />
            {(["login", "register"] as Tab[]).map((t) => (
              <button
                key={t}
                type="button"
                onClick={() => switchTab(t)}
                className={`flex-1 pb-3 text-[0.9rem] font-semibold transition-colors duration-150 focus-visible:outline-none
                  ${tab === t ? "text-primary" : "text-muted-foreground hover:text-foreground"}`}
              >
                {t === "login" ? "登录" : "注册"}
              </button>
            ))}
          </div>

          {/* ── Login form ── */}
          {tab === "login" && (
            <div className="flex flex-col gap-4">
              <FormInput
                type="text"
                value={loginUsername}
                onChange={(v) => setLoginUsername(filterUsername(v))}
                onBlur={() => setLoginErrors((e) => ({ ...e, username: validateUsername(loginUsername) }))}
                placeholder="请输入用户名（4-16 位字母/数字）"
                error={loginErrors.username}
                autoComplete="username"
              />

              <FormInput
                type={loginShowPw ? "text" : "password"}
                value={loginPassword}
                onChange={(v) => setLoginPassword(v)}
                onBlur={() => setLoginErrors((e) => ({ ...e, password: validatePassword(loginPassword) }))}
                placeholder="请输入密码（最少 6 位）"
                error={loginErrors.password}
                autoComplete="current-password"
                right={<EyeToggle show={loginShowPw} onToggle={() => setLoginShowPw((s) => !s)} />}
              />

              {loginApiError && (
                <div className="flex items-center gap-2 px-3.5 py-2.5 rounded-xl bg-red-50 border border-red-200">
                  <AlertCircle size={14} className="text-red-500 flex-shrink-0" strokeWidth={2} />
                  <span className="text-[0.875rem] text-red-600">{loginApiError}</span>
                </div>
              )}

              <button
                type="button"
                onClick={handleLogin}
                disabled={!loginCanSubmit() || loginLoading}
                className={`mt-1 w-full flex items-center justify-center gap-2 py-3 rounded-xl text-[0.9375rem] font-semibold transition-all duration-150 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring
                  ${loginCanSubmit() && !loginLoading
                    ? "bg-primary text-white hover:bg-blue-700 active:scale-[0.99] shadow-sm"
                    : "bg-muted text-muted-foreground cursor-not-allowed"
                  }`}
              >
                {loginLoading && <Loader2 size={16} strokeWidth={2} className="animate-spin" />}
                {loginLoading ? "登录中" : "登录"}
              </button>

              <p className="text-center text-[0.8125rem] text-muted-foreground">
                还没有账号？{" "}
                <button
                  type="button"
                  onClick={() => switchTab("register")}
                  className="text-primary font-medium hover:underline underline-offset-2"
                >
                  去注册
                </button>
              </p>

              {/* Dev hint */}
              <div className="mt-1 rounded-lg bg-muted/60 border border-border px-3.5 py-2.5 text-[0.78rem] text-muted-foreground leading-relaxed">
                <span className="font-semibold text-foreground">测试账号</span>　teststudent / 123456
              </div>
            </div>
          )}

          {/* ── Register form ── */}
          {tab === "register" && (
            <div className="flex flex-col gap-4">
              <FormInput
                type="text"
                value={regUsername}
                onChange={(v) => setRegUsername(filterUsername(v))}
                onBlur={() => setRegErrors((e) => ({ ...e, username: validateUsername(regUsername) }))}
                placeholder="设置用户名（4-16 位字母/数字）"
                error={regErrors.username}
                autoComplete="username"
              />

              <FormInput
                type={regShowPw ? "text" : "password"}
                value={regPassword}
                onChange={(v) => setRegPassword(v)}
                onBlur={() => setRegErrors((e) => ({ ...e, password: validatePassword(regPassword) }))}
                placeholder="设置密码（至少 6 位）"
                error={regErrors.password}
                autoComplete="new-password"
                right={<EyeToggle show={regShowPw} onToggle={() => setRegShowPw((s) => !s)} />}
              />

              <FormInput
                type={regShowConfirm ? "text" : "password"}
                value={regConfirm}
                onChange={(v) => setRegConfirm(v)}
                onBlur={() => setRegErrors((e) => ({ ...e, confirm: validateConfirm(regPassword, regConfirm) }))}
                placeholder="再次输入密码"
                error={regErrors.confirm}
                autoComplete="new-password"
                right={<EyeToggle show={regShowConfirm} onToggle={() => setRegShowConfirm((s) => !s)} />}
              />

              {regApiError && (
                <div className="flex items-center gap-2 px-3.5 py-2.5 rounded-xl bg-red-50 border border-red-200">
                  <AlertCircle size={14} className="text-red-500 flex-shrink-0" strokeWidth={2} />
                  <span className="text-[0.875rem] text-red-600">{regApiError}</span>
                </div>
              )}

              <button
                type="button"
                onClick={handleRegister}
                disabled={!regCanSubmit() || regLoading}
                className={`mt-1 w-full flex items-center justify-center gap-2 py-3 rounded-xl text-[0.9375rem] font-semibold transition-all duration-150 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring
                  ${regCanSubmit() && !regLoading
                    ? "bg-primary text-white hover:bg-blue-700 active:scale-[0.99] shadow-sm"
                    : "bg-muted text-muted-foreground cursor-not-allowed"
                  }`}
              >
                {regLoading && <Loader2 size={16} strokeWidth={2} className="animate-spin" />}
                {regLoading ? "注册中" : "注册"}
              </button>

              <p className="text-center text-[0.8125rem] text-muted-foreground">
                已有账号？{" "}
                <button
                  type="button"
                  onClick={() => switchTab("login")}
                  className="text-primary font-medium hover:underline underline-offset-2"
                >
                  去登录
                </button>
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
