// Design chat interface722/src/app/pages/SelectPage.tsx
import { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router";
import { ChevronDown, ArrowRight, BookOpen, Tag, FileText, Layers } from "lucide-react";
import { Toaster, toast } from "sonner";
import { UserMenu } from "../components/UserMenu";

/* ─── Types ─── */
type Subject = "computer" | "math" | "politics";

interface KnowledgePoint {
  kp_id: string;
  name: string;
  summary: string;
  tag?: string;
}

interface ChapterNode {
  chapter_id: string;
  title: string;
  knowledge_points: KnowledgePoint[];
}

interface MaterialNode {
  material_id: string;
  title: string;
  chapters: ChapterNode[];
}

/* ─── Mock data ─── */
const MOCK_TREE: Record<Subject, MaterialNode[]> = {
  computer: [
    {
      material_id: "mat-demo",
      title: "数据结构教材",
      chapters: [
        {
          chapter_id: "ch-demo",
          title: "第6章 图论",
          knowledge_points: [
            { kp_id: "kp-demo", name: "Dijkstra 算法", summary: "非负权图求单源最短路径的贪心算法", tag: "高频考点" },
            { kp_id: "kp-mst", name: "最小生成树", summary: "连通图总权值最小的生成子图" },
            { kp_id: "kp-topo", name: "拓扑排序", summary: "有向无环图节点线性排序方式" },
          ],
        },
        { chapter_id: "ch-tree", title: "第5章 树结构", knowledge_points: [] },
      ],
    },
    { material_id: "mat-os", title: "操作系统教材", chapters: [] },
  ],
  math: [],
  politics: [],
};

const MOCK_GREETING: Record<string, string> = {
  "kp-demo": "请你向我讲解一下 Dijkstra 算法的核心原理，讲得越详细越好。",
  "kp-mst": "请你向我讲解一下最小生成树的概念与常见算法。",
  "kp-topo": "请你向我讲解一下拓扑排序的原理和适用场景。",
};

const SUBJECT_LABELS: Record<Subject, string> = {
  computer: "计算机",
  math: "数学",
  politics: "政治",
};

/* ─── Custom dropdown ─── */
interface DropdownOption { value: string; label: string; disabled?: boolean }

function Dropdown({
  value,
  options,
  onChange,
  placeholder,
  disabled,
  icon: Icon,
}: {
  value: string;
  options: DropdownOption[];
  onChange: (v: string) => void;
  placeholder?: string;
  disabled?: boolean;
  icon: typeof ChevronDown;
}) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  const selected = options.find((o) => o.value === value);

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, []);

  return (
    <div ref={ref} className="relative">
      <button
        type="button"
        disabled={disabled}
        onClick={() => !disabled && setOpen((o) => !o)}
        className={`w-full flex items-center gap-2.5 px-4 py-3 rounded-xl border text-[0.9rem] transition-all duration-150 text-left
          ${disabled
            ? "bg-muted border-border text-muted-foreground cursor-not-allowed opacity-60"
            : "bg-card border-border text-foreground hover:border-primary/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring cursor-pointer"
          }
          ${open ? "border-primary ring-2 ring-ring" : ""}
        `}
      >
        <Icon size={15} className="text-muted-foreground flex-shrink-0" strokeWidth={1.8} />
        <span className={`flex-1 truncate ${selected ? "text-foreground" : "text-muted-foreground"}`}>
          {selected ? selected.label : (placeholder ?? "请选择")}
        </span>
        <ChevronDown
          size={15}
          strokeWidth={2}
          className={`text-muted-foreground flex-shrink-0 transition-transform duration-150 ${open ? "rotate-180" : ""}`}
        />
      </button>

      {open && (
        <div className="absolute z-50 left-0 right-0 mt-1.5 bg-card border border-border rounded-xl shadow-xl overflow-hidden">
          {options.map((opt) => (
            <button
              key={opt.value}
              type="button"
              disabled={opt.disabled}
              onClick={() => {
                if (!opt.disabled) {
                  onChange(opt.value);
                  setOpen(false);
                }
              }}
              className={`w-full text-left px-4 py-2.5 text-[0.875rem] transition-colors
                ${opt.disabled ? "text-muted-foreground cursor-not-allowed" : ""}
                ${opt.value === value && !opt.disabled
                  ? "bg-primary/8 text-primary font-semibold"
                  : !opt.disabled ? "text-foreground hover:bg-muted" : ""
                }`}
            >
              {opt.label}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

/* ─── KP radio card ─── */
function KpCard({
  kp,
  selected,
  onClick,
}: {
  kp: KnowledgePoint;
  selected: boolean;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`w-full flex items-start gap-3 px-4 py-3.5 rounded-xl border text-left transition-all duration-150 group
        ${selected
          ? "border-primary bg-primary/5 shadow-sm"
          : "border-border bg-card hover:border-primary/40 hover:bg-muted/30"
        }`}
    >
      {/* Radio indicator */}
      <div className={`flex-shrink-0 mt-[3px] w-4 h-4 rounded-full border-2 flex items-center justify-center transition-all
        ${selected ? "border-primary bg-primary" : "border-muted-foreground/40 group-hover:border-primary/60"}`}
      >
        {selected && <div className="w-1.5 h-1.5 rounded-full bg-white" />}
      </div>

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 flex-wrap">
          <span className={`text-[0.9375rem] font-medium leading-snug ${selected ? "text-primary" : "text-foreground"}`}>
            {kp.name}
          </span>
          {kp.tag && (
            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-amber-100 text-amber-700 text-[0.7rem] font-semibold leading-none">
              <Tag size={9} strokeWidth={2.5} />
              {kp.tag}
            </span>
          )}
        </div>
        <p className="text-[0.8125rem] text-muted-foreground mt-0.5 leading-snug">{kp.summary}</p>
      </div>
    </button>
  );
}

/* ─── Section wrapper ─── */
function Section({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-2">
      <div className="text-[0.75rem] font-semibold text-muted-foreground uppercase tracking-wider pl-0.5">
        {label}
      </div>
      {children}
    </div>
  );
}

/* ─── Main page ─── */
export default function SelectPage() {
  const navigate = useNavigate();

  const [subject, setSubject] = useState<Subject>("computer");
  const [materials, setMaterials] = useState<MaterialNode[]>([]);
  const [selectedMaterialId, setSelectedMaterialId] = useState<string>("");
  const [selectedChapterId, setSelectedChapterId] = useState<string>("");
  const [selectedKpId, setSelectedKpId] = useState<string>("");
  const [greetingText, setGreetingText] = useState<string>("");
  const [loading, setLoading] = useState(false);

  /* ── Derived values ── */
  const selectedMaterial = materials.find((m) => m.material_id === selectedMaterialId);
  const chapters = selectedMaterial?.chapters ?? [];
  const selectedChapter = chapters.find((c) => c.chapter_id === selectedChapterId);
  const kps = selectedChapter?.knowledge_points ?? [];
  const selectedKp = kps.find((k) => k.kp_id === selectedKpId);

  const materialOptions: DropdownOption[] =
    materials.length === 0
      ? [{ value: "", label: "暂无教材", disabled: true }]
      : materials.map((m) => ({ value: m.material_id, label: m.title }));

  const chapterOptions: DropdownOption[] =
    !selectedMaterial
      ? []
      : chapters.length === 0
        ? [{ value: "", label: "暂无章节", disabled: true }]
        : chapters.map((c) => ({ value: c.chapter_id, label: c.title }));

  const showChapters = !!selectedMaterialId;
  const showKps = !!selectedChapterId;

  /* ── Load subject tree (mock) ── */
  async function loadTree(subj: Subject) {
    setLoading(true);
    await new Promise((r) => setTimeout(r, 300)); // simulate network
    try {
      const data = MOCK_TREE[subj];
      setMaterials(data);
      // auto-select first material
      const firstMat = data[0];
      if (firstMat) {
        setSelectedMaterialId(firstMat.material_id);
        const firstCh = firstMat.chapters[0];
        if (firstCh) {
          setSelectedChapterId(firstCh.chapter_id);
          const firstKp = firstCh.knowledge_points[0];
          if (firstKp) {
            setSelectedKpId(firstKp.kp_id);
            loadGreeting(firstKp.kp_id);
          } else {
            setSelectedKpId("");
          }
        } else {
          setSelectedChapterId("");
          setSelectedKpId("");
        }
      } else {
        setSelectedMaterialId("");
        setSelectedChapterId("");
        setSelectedKpId("");
      }
    } catch {
      toast.error("加载数据失败，请重新切换选项");
    } finally {
      setLoading(false);
    }
  }

  async function loadGreeting(kpId: string) {
    await new Promise((r) => setTimeout(r, 200));
    const text = MOCK_GREETING[kpId];
    if (text) setGreetingText(text);
  }

  /* ── Init ── */
  useEffect(() => {
    loadTree("computer");
  }, []);

  /* ── Handlers ── */
  function handleSubjectChange(v: string) {
    const s = v as Subject;
    setSubject(s);
    setSelectedMaterialId("");
    setSelectedChapterId("");
    setSelectedKpId("");
    setGreetingText("");
    loadTree(s);
  }

  function handleMaterialChange(v: string) {
    setSelectedMaterialId(v);
    setSelectedChapterId("");
    setSelectedKpId("");
    setGreetingText("");
    const mat = materials.find((m) => m.material_id === v);
    const firstCh = mat?.chapters[0];
    if (firstCh) {
      setSelectedChapterId(firstCh.chapter_id);
      const firstKp = firstCh.knowledge_points[0];
      if (firstKp) {
        setSelectedKpId(firstKp.kp_id);
        loadGreeting(firstKp.kp_id);
      }
    }
  }

  function handleChapterChange(v: string) {
    setSelectedChapterId(v);
    setSelectedKpId("");
    setGreetingText("");
    const ch = chapters.find((c) => c.chapter_id === v);
    const firstKp = ch?.knowledge_points[0];
    if (firstKp) {
      setSelectedKpId(firstKp.kp_id);
      loadGreeting(firstKp.kp_id);
    }
  }

  function handleKpSelect(kpId: string) {
    setSelectedKpId(kpId);
    loadGreeting(kpId);
  }

  function handleStart() {
    if (!selectedKpId) return;
    navigate(
      `/?kp_id=${selectedKpId}&material_id=${selectedMaterialId}&chapter_id=${selectedChapterId}&subject=${subject}`
    );
  }

  const canStart = !!selectedKpId;

  return (
    <div
      className="min-h-screen bg-background flex flex-col"
      style={{ fontFamily: "'Noto Sans SC', 'Inter', sans-serif" }}
    >
      <Toaster position="top-center" richColors />

      {/* Header */}
      <header className="sticky top-0 z-30 bg-card border-b border-border h-14 flex items-center px-6">
        <h1 className="text-[0.9375rem] font-semibold text-foreground flex-1">选择知识点开始费曼学习</h1>
        <UserMenu />
      </header>

      <main className="flex-1 flex flex-col max-w-xl w-full mx-auto px-4 py-8 gap-0">
        {/* Cascade selectors */}
        <div className="flex flex-col gap-0">

          {/* ── Subject ── */}
          <CascadeRow step={1} label="科目" last={false}>
            <Dropdown
              value={subject}
              options={(Object.keys(SUBJECT_LABELS) as Subject[]).map((s) => ({
                value: s,
                label: SUBJECT_LABELS[s],
              }))}
              onChange={handleSubjectChange}
              icon={Layers}
            />
          </CascadeRow>

          {/* ── Material ── */}
          <CascadeRow step={2} label="教材" last={false}>
            <Dropdown
              value={selectedMaterialId}
              options={materialOptions}
              onChange={handleMaterialChange}
              placeholder="请选择教材"
              disabled={materials.length === 0 || loading}
              icon={FileText}
            />
          </CascadeRow>

          {/* ── Chapter ── */}
          <CascadeRow step={3} label="章节" last={false}>
            {showChapters ? (
              <Dropdown
                value={selectedChapterId}
                options={chapterOptions}
                onChange={handleChapterChange}
                placeholder="请选择章节"
                disabled={chapterOptions.length === 0 || (chapterOptions[0]?.disabled ?? false)}
                icon={BookOpen}
              />
            ) : (
              <div className="w-full px-4 py-3 rounded-xl border border-border bg-muted text-muted-foreground text-[0.9rem] opacity-50 cursor-not-allowed select-none flex items-center gap-2.5">
                <BookOpen size={15} strokeWidth={1.8} />
                请先选择教材
              </div>
            )}
          </CascadeRow>

          {/* ── Knowledge points ── */}
          <CascadeRow step={4} label="知识点" last={true}>
            {!showKps ? (
              <div className="w-full px-4 py-3 rounded-xl border border-border bg-muted text-muted-foreground text-[0.9rem] opacity-50 select-none flex items-center gap-2.5">
                <Tag size={15} strokeWidth={1.8} />
                请先选择章节
              </div>
            ) : kps.length === 0 ? (
              <div className="w-full px-4 py-4 rounded-xl border border-border bg-card text-muted-foreground text-[0.875rem] text-center leading-relaxed">
                当前章节暂无知识点，请前往<button
                  onClick={() => navigate("/upload")}
                  className="text-primary underline underline-offset-2 mx-0.5"
                >教材管理</button>页面新增
              </div>
            ) : (
              <div className="flex flex-col gap-1.5">
                {kps.map((kp) => (
                  <KpCard
                    key={kp.kp_id}
                    kp={kp}
                    selected={selectedKpId === kp.kp_id}
                    onClick={() => handleKpSelect(kp.kp_id)}
                  />
                ))}
              </div>
            )}
          </CascadeRow>
        </div>

        {/* Greeting preview */}
        {greetingText && selectedKp && (
          <div className="mt-6 rounded-xl bg-blue-50 border border-blue-100 px-4 py-3.5 flex gap-3 items-start">
            <div className="flex-shrink-0 w-7 h-7 rounded-full bg-blue-200 flex items-center justify-center mt-0.5">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" aria-hidden="true">
                <rect x="5" y="8" width="14" height="10" rx="2" fill="#2563EB" />
                <rect x="9" y="11" width="2" height="2" rx="0.5" fill="#fff" />
                <rect x="13" y="11" width="2" height="2" rx="0.5" fill="#fff" />
                <rect x="10.5" y="5" width="3" height="3" rx="1" fill="#2563EB" />
                <circle cx="12" cy="4.5" r="1" fill="#60A5FA" />
              </svg>
            </div>
            <div>
              <div className="text-[0.75rem] font-semibold text-blue-600 mb-1 uppercase tracking-wider">引导语预览</div>
              <p className="text-[0.875rem] text-blue-900 leading-relaxed">{greetingText}</p>
            </div>
          </div>
        )}
      </main>

      {/* Sticky footer CTA */}
      <div className="sticky bottom-0 bg-card border-t border-border px-4 py-4">
        <div className="max-w-xl mx-auto">
          <button
            onClick={handleStart}
            disabled={!canStart}
            className={`w-full flex items-center justify-center gap-2 py-3.5 rounded-xl font-semibold text-[1rem] transition-all duration-150 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring
              ${canStart
                ? "bg-primary text-primary-foreground hover:bg-blue-700 active:scale-[0.99] shadow-sm shadow-primary/20"
                : "bg-muted text-muted-foreground cursor-not-allowed"
              }`}
          >
            开始费曼讲解
            <ArrowRight size={18} strokeWidth={2.5} className={canStart ? "text-white" : "text-muted-foreground"} />
          </button>
          {!canStart && (
            <p className="text-center text-[0.8125rem] text-muted-foreground mt-2">请先选择一个知识点</p>
          )}
        </div>
      </div>
    </div>
  );
}

/* ─── Cascade row with connector line ─── */
function CascadeRow({
  step,
  label,
  last,
  children,
}: {
  step: number;
  label: string;
  last: boolean;
  children: React.ReactNode;
}) {
  return (
    <div className="flex gap-4">
      {/* Step indicator column */}
      <div className="flex flex-col items-center flex-shrink-0 w-8 pt-3">
        <div className="w-7 h-7 rounded-full bg-primary flex items-center justify-center flex-shrink-0 shadow-sm">
          <span className="text-[0.7rem] font-bold text-white leading-none">{step}</span>
        </div>
        {!last && <div className="flex-1 w-px bg-border mt-1 mb-1 min-h-[1.5rem]" />}
      </div>

      {/* Content */}
      <div className={`flex-1 min-w-0 ${last ? "pb-0" : "pb-5"}`}>
        <div className="text-[0.8125rem] font-semibold text-muted-foreground mb-2 pt-1.5">{label}</div>
        {children}
      </div>
    </div>
  );
}

// frontend/src/views/SelectPage.vue
<script setup>
import { ref, onMounted, watch, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useChatStore } from '@/stores/chatStore'
import { getKnowledgeTree, fetchGreeting } from '@/api/feynman'

const router = useRouter()
const chatStore = useChatStore()

const subjects = [
  { value: 'computer', label: '计算机' },
  { value: 'math', label: '数学' },
  { value: 'politics', label: '政治' }
]

const selectedSubject = ref('computer')
const knowledgeTree = ref([])
const selectedMaterialId = ref('')
const selectedChapterId = ref('')
const selectedKpId = ref('')
const greetingText = ref('')
const loading = ref(false)

const dropdownOpen = ref({})

const materials = computed(() => knowledgeTree.value || [])
const chapters = computed(() => {
  const material = materials.value.find(m => m.material_id === selectedMaterialId.value)
  return material?.chapters || []
})
const knowledgePoints = computed(() => {
  const chapter = chapters.value.find(c => c.chapter_id === selectedChapterId.value)
  return chapter?.knowledge_points || []
})
const selectedKp = computed(() => {
  return knowledgePoints.value.find(kp => kp.kp_id === selectedKpId.value)
})

const canStart = computed(() => !!selectedKpId.value)
const showChapters = computed(() => !!selectedMaterialId.value)
const showKps = computed(() => !!selectedChapterId.value)

const materialOptions = computed(() => {
  if (materials.value.length === 0) {
    return [{ value: '', label: '暂无教材', disabled: true }]
  }
  return materials.value.map(m => ({ value: m.material_id, label: m.title }))
})

const chapterOptions = computed(() => {
  if (!selectedMaterialId.value) return []
  if (chapters.value.length === 0) {
    return [{ value: '', label: '暂无章节', disabled: true }]
  }
  return chapters.value.map(c => ({ value: c.chapter_id, label: c.title }))
})

async function loadKnowledgeTree() {
  loading.value = true
  try {
    const data = await getKnowledgeTree(selectedSubject.value)
    knowledgeTree.value = data
    if (data.length > 0) {
      selectedMaterialId.value = data[0].material_id
      const firstCh = data[0].chapters[0]
      if (firstCh) {
        selectedChapterId.value = firstCh.chapter_id
        const firstKp = firstCh.knowledge_points[0]
        if (firstKp) {
          selectedKpId.value = firstKp.kp_id
          loadGreeting(firstKp.kp_id)
        } else {
          selectedKpId.value = ''
        }
      } else {
        selectedChapterId.value = ''
        selectedKpId.value = ''
      }
    } else {
      selectedMaterialId.value = ''
      selectedChapterId.value = ''
      selectedKpId.value = ''
    }
  } catch (e) {
    showToastMsg('加载数据失败，请重新切换选项')
  } finally {
    loading.value = false
  }
}

async function loadGreeting(kpId) {
  try {
    const greeting = await fetchGreeting(kpId)
    greetingText.value = greeting.reply_text
  } catch (e) {
    console.warn('预加载 greeting 失败:', e)
  }
}

function handleSubjectChange(v) {
  selectedSubject.value = v
  selectedMaterialId.value = ''
  selectedChapterId.value = ''
  selectedKpId.value = ''
  greetingText.value = ''
  loadKnowledgeTree()
}

function handleMaterialChange(v) {
  selectedMaterialId.value = v
  selectedChapterId.value = ''
  selectedKpId.value = ''
  greetingText.value = ''
  const mat = materials.value.find(m => m.material_id === v)
  const firstCh = mat?.chapters[0]
  if (firstCh) {
    selectedChapterId.value = firstCh.chapter_id
    const firstKp = firstCh.knowledge_points[0]
    if (firstKp) {
      selectedKpId.value = firstKp.kp_id
      loadGreeting(firstKp.kp_id)
    }
  }
}

function handleChapterChange(v) {
  selectedChapterId.value = v
  selectedKpId.value = ''
  greetingText.value = ''
  const ch = chapters.value.find(c => c.chapter_id === v)
  const firstKp = ch?.knowledge_points[0]
  if (firstKp) {
    selectedKpId.value = firstKp.kp_id
    loadGreeting(firstKp.kp_id)
  }
}

function handleKpSelect(kpId) {
  selectedKpId.value = kpId
  loadGreeting(kpId)
}

async function startFeynman() {
  if (!selectedKp.value) return
  const kp = selectedKp.value
  const material = materials.value.find(m => m.material_id === selectedMaterialId.value)
  const chapter = chapters.value.find(c => c.chapter_id === selectedChapterId.value)
  const subjectLabel = subjects.find(s => s.value === selectedSubject.value)?.label || ''
  
  chatStore.setSubject(subjectLabel)
  chatStore.setMaterial(selectedMaterialId.value, material?.title || '')
  chatStore.setChapter(selectedChapterId.value, chapter?.title || '')
  chatStore.setKnowledgePoint(kp.kp_id, kp.name)
  router.push('/home')
}

function showToastMsg(msg) {
  toastMessage.value = msg
  showToast.value = true
  setTimeout(() => {
    showToast.value = false
  }, 3000)
}

function goToUploadPage() {
  router.push('/upload')
}

function toggleDropdown(key) {
  dropdownOpen.value[key] = !dropdownOpen.value[key]
}

function closeDropdown(key) {
  dropdownOpen.value[key] = false
}

const toastMessage = ref('')
const showToast = ref(false)

onMounted(() => {
  loadKnowledgeTree()
  document.addEventListener('click', (e) => {
    if (!e.target.closest('.dropdown-wrapper')) {
      Object.keys(dropdownOpen.value).forEach(key => {
        dropdownOpen.value[key] = false
      })
    }
  })
})
</script>

<template>
  <div class="select-page">
    <header class="select-header">
      <h1 class="page-title">选择知识点开始费曼学习</h1>
    </header>

    <main class="select-main">
      <div class="cascade-container">
        <div class="cascade-row">
          <div class="cascade-step">
            <div class="step-circle">1</div>
            <div class="step-line"></div>
          </div>
          <div class="cascade-content">
            <div class="cascade-label">科目</div>
            <div class="dropdown-wrapper">
              <button class="dropdown-btn" @click="toggleDropdown('subject')">
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
                  <rect x="3" y="3" width="7" height="7" rx="1" />
                  <rect x="14" y="3" width="7" height="7" rx="1" />
                  <rect x="3" y="14" width="7" height="7" rx="1" />
                  <rect x="14" y="14" width="7" height="7" rx="1" />
                </svg>
                <span>{{ subjects.find(s => s.value === selectedSubject)?.label }}</span>
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" :class="{ 'rotate-180': dropdownOpen['subject'] }">
                  <polyline points="6 9 12 15 18 9" />
                </svg>
              </button>
              <div v-if="dropdownOpen['subject']" class="dropdown-menu">
                <button
                  v-for="s in subjects"
                  :key="s.value"
                  class="dropdown-item"
                  :class="{ 'dropdown-item--selected': s.value === selectedSubject }"
                  @click="handleSubjectChange(s.value); closeDropdown('subject')"
                >
                  {{ s.label }}
                </button>
              </div>
            </div>
          </div>
        </div>

        <div class="cascade-row">
          <div class="cascade-step">
            <div class="step-circle">2</div>
            <div class="step-line"></div>
          </div>
          <div class="cascade-content">
            <div class="cascade-label">教材</div>
            <div class="dropdown-wrapper">
              <button
                class="dropdown-btn"
                :disabled="materials.length === 0 || loading"
                @click="toggleDropdown('material')"
              >
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                  <polyline points="14 2 14 8 20 8" />
                  <line x1="16" y1="13" x2="8" y2="13" />
                  <line x1="16" y1="17" x2="8" y2="17" />
                  <polyline points="10 9 9 9 8 9" />
                </svg>
                <span>{{ materialOptions.find(o => o.value === selectedMaterialId)?.label || '请选择教材' }}</span>
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" :class="{ 'rotate-180': dropdownOpen['material'] }">
                  <polyline points="6 9 12 15 18 9" />
                </svg>
              </button>
              <div v-if="dropdownOpen['material']" class="dropdown-menu">
                <button
                  v-for="opt in materialOptions"
                  :key="opt.value"
                  class="dropdown-item"
                  :class="{ 'dropdown-item--selected': opt.value === selectedMaterialId, 'dropdown-item--disabled': opt.disabled }"
                  :disabled="opt.disabled"
                  @click="!opt.disabled && (handleMaterialChange(opt.value), closeDropdown('material'))"
                >
                  {{ opt.label }}
                </button>
              </div>
            </div>
          </div>
        </div>

        <div class="cascade-row">
          <div class="cascade-step">
            <div class="step-circle">3</div>
            <div class="step-line"></div>
          </div>
          <div class="cascade-content">
            <div class="cascade-label">章节</div>
            <div v-if="showChapters" class="dropdown-wrapper">
              <button
                class="dropdown-btn"
                :disabled="chapterOptions.length === 0 || (chapterOptions[0]?.disabled ?? false)"
                @click="toggleDropdown('chapter')"
              >
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
                  <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
                  <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
                </svg>
                <span>{{ chapterOptions.find(o => o.value === selectedChapterId)?.label || '请选择章节' }}</span>
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" :class="{ 'rotate-180': dropdownOpen['chapter'] }">
                  <polyline points="6 9 12 15 18 9" />
                </svg>
              </button>
              <div v-if="dropdownOpen['chapter']" class="dropdown-menu">
                <button
                  v-for="opt in chapterOptions"
                  :key="opt.value"
                  class="dropdown-item"
                  :class="{ 'dropdown-item--selected': opt.value === selectedChapterId, 'dropdown-item--disabled': opt.disabled }"
                  :disabled="opt.disabled"
                  @click="!opt.disabled && (handleChapterChange(opt.value), closeDropdown('chapter'))"
                >
                  {{ opt.label }}
                </button>
              </div>
            </div>
            <div v-else class="placeholder-box">
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
                <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
                <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
              </svg>
              请先选择教材
            </div>
          </div>
        </div>

        <div class="cascade-row">
          <div class="cascade-step">
            <div class="step-circle">4</div>
          </div>
          <div class="cascade-content">
            <div class="cascade-label">知识点</div>
            <div v-if="!showKps" class="placeholder-box">
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
                <path d="M12 2L2 7l10 5 10-5-10-5z" />
                <path d="M2 17l10 5 10-5" />
                <path d="M2 12l10 5 10-5" />
              </svg>
              请先选择章节
            </div>
            <div v-else-if="knowledgePoints.length === 0" class="empty-kp-box">
              当前章节暂无知识点，请前往
              <button class="link-btn" @click="goToUploadPage">教材管理</button>
              页面新增
            </div>
            <div v-else class="kp-list">
              <button
                v-for="kp in knowledgePoints"
                :key="kp.kp_id"
                class="kp-card"
                :class="{ 'kp-card--selected': selectedKpId === kp.kp_id }"
                @click="handleKpSelect(kp.kp_id)"
              >
                <div class="kp-radio" :class="{ 'kp-radio--selected': selectedKpId === kp.kp_id }">
                  <div v-if="selectedKpId === kp.kp_id" class="radio-inner"></div>
                </div>
                <div class="kp-content">
                  <div class="kp-name">
                    {{ kp.name }}
                  </div>
                  <div v-if="kp.summary" class="kp-summary">{{ kp.summary }}</div>
                </div>
              </button>
            </div>
          </div>
        </div>
      </div>

      <div v-if="greetingText && selectedKp" class="greeting-preview">
        <div class="greeting-avatar">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <rect x="5" y="8" width="14" height="10" rx="2" fill="#2563EB" />
            <rect x="9" y="11" width="2" height="2" rx="0.5" fill="#fff" />
            <rect x="13" y="11" width="2" height="2" rx="0.5" fill="#fff" />
            <rect x="10.5" y="5" width="3" height="3" rx="1" fill="#2563EB" />
            <circle cx="12" cy="4.5" r="1" fill="#60A5FA" />
          </svg>
        </div>
        <div class="greeting-content">
          <div class="greeting-label">引导语预览</div>
          <p class="greeting-text">{{ greetingText }}</p>
        </div>
      </div>
    </main>

    <footer class="select-footer">
      <div class="footer-inner">
        <button
          class="start-btn"
          :disabled="!canStart"
          @click="startFeynman"
        >
          <span>开始费曼讲解</span>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
            <path d="M5 12h14M12 5l7 7-7 7" />
          </svg>
        </button>
        <p v-if="!canStart" class="footer-hint">请先选择一个知识点</p>
      </div>
    </footer>

    <div v-if="showToast" class="toast">{{ toastMessage }}</div>
  </div>
</template>

<style scoped>
.select-page {
  min-height: 100vh;
  background: #F8FAFC;
  display: flex;
  flex-direction: column;
  font-family: 'Noto Sans SC', 'Inter', sans-serif;
}

.select-header {
  position: sticky;
  top: 0;
  z-index: 30;
  background: #FFFFFF;
  border-bottom: 1px solid #E2E8F0;
  height: 56px;
  display: flex;
  align-items: center;
  padding: 0 24px;
}

.page-title {
  font-size: 15px;
  font-weight: 600;
  color: #1E293B;
}

.select-main {
  flex: 1;
  padding: 32px 16px;
  max-width: 480px;
  margin: 0 auto;
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 0;
}

.cascade-container {
  display: flex;
  flex-direction: column;
  gap: 0;
}

.cascade-row {
  display: flex;
  gap: 16px;
}

.cascade-step {
  display: flex;
  flex-direction: column;
  align-items: center;
  flex-shrink: 0;
  width: 32px;
  padding-top: 12px;
}

.step-circle {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  background: #2563EB;
  color: #FFFFFF;
  font-size: 12px;
  font-weight: 700;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  box-shadow: 0 1px 2px rgba(37, 99, 235, 0.2);
}

.step-line {
  flex: 1;
  width: 2px;
  background: #E2E8F0;
  margin: 4px 0;
  min-height: 24px;
}

.cascade-content {
  flex: 1;
  min-width: 0;
  padding-bottom: 20px;
}

.cascade-label {
  font-size: 13px;
  font-weight: 600;
  color: #64748B;
  margin-bottom: 8px;
  padding-top: 6px;
}

.dropdown-wrapper {
  position: relative;
}

.dropdown-btn {
  width: 100%;
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 12px 16px;
  border-radius: 12px;
  border: 1px solid #E2E8F0;
  font-size: 14px;
  color: #1E293B;
  background: #FFFFFF;
  transition: all 150ms;
}

.dropdown-btn:hover:not(:disabled) {
  border-color: rgba(37, 99, 235, 0.5);
}

.dropdown-btn:focus-visible {
  outline: none;
  border-color: #2563EB;
  box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.1);
}

.dropdown-btn:disabled {
  background: #F1F5F9;
  color: #94A3B8;
  cursor: not-allowed;
  opacity: 0.6;
}

.dropdown-btn svg {
  color: #64748B;
}

.dropdown-btn span {
  flex: 1;
  text-align: left;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.dropdown-menu {
  position: absolute;
  z-index: 50;
  left: 0;
  right: 0;
  top: calc(100% + 6px);
  background: #FFFFFF;
  border: 1px solid #E2E8F0;
  border-radius: 12px;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);
  overflow: hidden;
}

.dropdown-item {
  width: 100%;
  text-align: left;
  padding: 10px 16px;
  font-size: 14px;
  color: #1E293B;
  transition: all 150ms;
}

.dropdown-item:hover:not(:disabled) {
  background: #F1F5F9;
}

.dropdown-item--selected {
  background: rgba(37, 99, 235, 0.08);
  color: #2563EB;
  font-weight: 600;
}

.dropdown-item--disabled {
  color: #94A3B8;
  cursor: not-allowed;
}

.placeholder-box {
  width: 100%;
  padding: 12px 16px;
  border-radius: 12px;
  border: 1px solid #E2E8F0;
  background: #F1F5F9;
  color: #94A3B8;
  font-size: 14px;
  opacity: 0.5;
  display: flex;
  align-items: center;
  gap: 10px;
  cursor: not-allowed;
  user-select: none;
}

.placeholder-box svg {
  color: #94A3B8;
}

.empty-kp-box {
  width: 100%;
  padding: 16px;
  border-radius: 12px;
  border: 1px solid #E2E8F0;
  background: #FFFFFF;
  color: #64748B;
  font-size: 14px;
  text-align: center;
  line-height: 1.6;
}

.link-btn {
  color: #2563EB;
  text-decoration: underline;
  text-underline-offset: 4px;
  font-weight: 500;
}

.kp-list {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.kp-card {
  width: 100%;
  display: flex;
  align-items: flex-start;
  gap: 12px;
  padding: 14px 16px;
  border-radius: 12px;
  border: 2px solid transparent;
  background: #FFFFFF;
  text-align: left;
  cursor: pointer;
  transition: all 150ms;
}

.kp-card:hover {
  background: #F8FAFC;
  border-color: rgba(37, 99, 235, 0.4);
}

.kp-card--selected {
  border-color: #2563EB;
  background: rgba(37, 99, 235, 0.04);
}

.kp-radio {
  width: 16px;
  height: 16px;
  border-radius: 50%;
  border: 2px solid #CBD5E1;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-top: 2px;
  transition: all 150ms;
}

.kp-radio--selected {
  border-color: #2563EB;
  background: #2563EB;
}

.radio-inner {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: #FFFFFF;
}

.kp-content {
  flex: 1;
  min-width: 0;
}

.kp-name {
  font-size: 15px;
  font-weight: 500;
  color: #1E293B;
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
}



.kp-summary {
  font-size: 13px;
  color: #64748B;
  margin-top: 4px;
  line-height: 1.5;
}

.greeting-preview {
  margin-top: 24px;
  padding: 14px 16px;
  border-radius: 12px;
  background: rgba(37, 99, 235, 0.04);
  border: 1px solid rgba(37, 99, 235, 0.1);
  display: flex;
  gap: 12px;
  align-items: flex-start;
}

.greeting-avatar {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  background: #DBEAFE;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  margin-top: 2px;
}

.greeting-content {
  flex: 1;
  min-width: 0;
}

.greeting-label {
  font-size: 12px;
  font-weight: 600;
  color: #2563EB;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  margin-bottom: 4px;
}

.greeting-text {
  font-size: 14px;
  color: #1E40AF;
  line-height: 1.6;
  margin: 0;
}

.select-footer {
  position: sticky;
  bottom: 0;
  background: #FFFFFF;
  border-top: 1px solid #E2E8F0;
  padding: 16px;
}

.footer-inner {
  max-width: 480px;
  margin: 0 auto;
}

.start-btn {
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 14px;
  border-radius: 12px;
  font-size: 16px;
  font-weight: 600;
  transition: all 150ms;
}

.start-btn:not(:disabled) {
  background: #2563EB;
  color: #FFFFFF;
  box-shadow: 0 2px 8px rgba(37, 99, 235, 0.25);
}

.start-btn:not(:disabled):hover {
  background: #1D4ED8;
}

.start-btn:not(:disabled):active {
  transform: scale(0.99);
}

.start-btn:disabled {
  background: #F1F5F9;
  color: #94A3B8;
  cursor: not-allowed;
}

.footer-hint {
  text-align: center;
  font-size: 13px;
  color: #94A3B8;
  margin: 8px 0 0 0;
}

.toast {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  padding: 12px 24px;
  background: rgba(15, 23, 42, 0.9);
  color: #FFFFFF;
  border-radius: 10px;
  font-size: 14px;
  z-index: 200;
}

.rotate-180 {
  transform: rotate(180deg);
}
</style>
