// Design chat interface722/src/app/pages/UploadPage.tsx
import { useState, useRef } from "react";
import { useNavigate } from "react-router";
import {
  Upload,
  ChevronDown,
  CheckCircle2,
  AlertCircle,
  FileText,
  Loader2,
} from "lucide-react";
import { Toaster, toast } from "sonner";
import { UserMenu } from "../components/UserMenu";

/* ─── Types ─── */
type Subject = "computer" | "math" | "politics";
type MaterialStatus = "parsing" | "chunking" | "extracting" | "generating" | "done" | "failed";

interface Material {
  id: string;
  name: string;
  status: MaterialStatus;
  step?: string;
  progress?: number;
  error?: string;
}

/* ─── Constants ─── */
const SUBJECT_LABELS: Record<Subject, string> = {
  computer: "计算机",
  math: "数学",
  politics: "政治",
};

const STEP_LABELS: Record<string, string> = {
  parsing: "解析中",
  chunking: "分块中",
  extracting: "抽取中",
  generating: "rubric生成中",
};

const PARSE_STEPS: Array<{ status: MaterialStatus; key: string; progress: number }> = [
  { status: "parsing", key: "parsing", progress: 20 },
  { status: "chunking", key: "chunking", progress: 45 },
  { status: "extracting", key: "extracting", progress: 70 },
  { status: "generating", key: "generating", progress: 88 },
];

const initialMaterials: Record<Subject, Material[]> = {
  computer: [
    { id: "m1", name: "数据结构教材.pdf", status: "generating", step: "generating", progress: 60 },
    { id: "m2", name: "操作系统教材.pdf", status: "done" },
  ],
  math: [],
  politics: [],
};

/* ─── Material item ─── */
function MaterialItem({
  material,
  onClick,
  onRetry,
}: {
  material: Material;
  onClick: () => void;
  onRetry: () => void;
}) {
  const isProcessing = ["parsing", "chunking", "extracting", "generating"].includes(material.status);
  const isDone = material.status === "done";
  const isFailed = material.status === "failed";

  return (
    <div
      onClick={isDone ? onClick : undefined}
      className={`flex items-center gap-3 bg-card border rounded-xl px-4 py-3.5 transition-all duration-150
        ${isDone
          ? "border-border cursor-pointer hover:border-primary/40 hover:shadow-sm hover:bg-blue-50/40"
          : "border-border cursor-default"
        }
      `}
    >
      <FileText
        size={18}
        className={`flex-shrink-0 ${isDone ? "text-primary/60" : "text-muted-foreground"}`}
        strokeWidth={1.8}
      />

      <div className="flex-1 min-w-0">
        <div className={`text-[0.9rem] font-medium truncate mb-1 ${isDone ? "text-foreground" : "text-foreground"}`}>
          {material.name}
        </div>

        {isProcessing && (
          <div className="flex flex-col gap-1.5">
            <div className="flex items-center justify-between">
              <span className="text-[0.8125rem] text-muted-foreground">
                {STEP_LABELS[material.step ?? ""] ?? material.step}
              </span>
              <span className="text-[0.8125rem] text-primary font-medium tabular-nums">
                {material.progress ?? 0}%
              </span>
            </div>
            <div className="h-1.5 bg-muted rounded-full overflow-hidden">
              <div
                className="h-1.5 bg-primary rounded-full transition-all duration-700"
                style={{ width: `${material.progress ?? 0}%` }}
              />
            </div>
          </div>
        )}

        {isDone && (
          <div className="flex items-center gap-1.5">
            <CheckCircle2 size={13} className="text-green-500" strokeWidth={2.5} />
            <span className="text-[0.8125rem] text-green-600 font-medium">已完成 · 点击查看知识点</span>
          </div>
        )}

        {isFailed && (
          <div className="flex items-center gap-1.5">
            <AlertCircle size={13} className="text-red-500" strokeWidth={2} />
            <span className="text-[0.8125rem] text-red-600">{material.error ?? "解析失败"}</span>
          </div>
        )}
      </div>

      {isProcessing && (
        <Loader2 size={15} className="text-primary flex-shrink-0 animate-spin" strokeWidth={2} />
      )}

      {isFailed && (
        <button
          onClick={(e) => { e.stopPropagation(); onRetry(); }}
          className="flex-shrink-0 text-[0.8125rem] font-semibold text-primary border border-primary/30 rounded-lg px-3 py-1.5 hover:bg-primary/5 transition-colors"
        >
          重试解析
        </button>
      )}
    </div>
  );
}

/* ─── Main page ─── */
export default function UploadPage() {
  const navigate = useNavigate();
  const [subject, setSubject] = useState<Subject>("computer");
  const [subjectOpen, setSubjectOpen] = useState(false);
  const [dragOver, setDragOver] = useState(false);
  const [materials, setMaterials] = useState<Record<Subject, Material[]>>(initialMaterials);
  const [uploadState, setUploadState] = useState<null | {
    progress: number;
    status: "uploading" | "error";
    errorMsg?: string;
    fileName?: string;
  }>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const dragCounterRef = useRef(0);
  const uploadTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const currentMaterials = materials[subject];
  const isUploading = uploadState?.status === "uploading";

  /* ── Helpers ── */
  function updateMaterial(id: string, subj: Subject, patch: Partial<Material>) {
    setMaterials((prev) => ({
      ...prev,
      [subj]: prev[subj].map((m) => (m.id === id ? { ...m, ...patch } : m)),
    }));
  }

  function simulateParsing(id: string, subj: Subject) {
    let idx = 0;
    const timer = setInterval(() => {
      if (idx >= PARSE_STEPS.length) {
        clearInterval(timer);
        updateMaterial(id, subj, { status: "done", step: undefined, progress: undefined });
        return;
      }
      const s = PARSE_STEPS[idx++];
      updateMaterial(id, subj, { status: s.status, step: s.key, progress: s.progress });
    }, 1800);
  }

  function validateAndUpload(file: File) {
    if (isUploading) return;
    const isPdf = file.name.toLowerCase().endsWith(".pdf") && file.type === "application/pdf";
    if (!isPdf) {
      toast.error("仅支持文字版PDF文件");
      return;
    }
    if (file.size > 50 * 1024 * 1024) {
      setUploadState({ status: "error", progress: 0, fileName: file.name, errorMsg: "文件超过50MB大小限制" });
      return;
    }
    startUpload(file);
  }

  function startUpload(file: File) {
    setUploadState({ progress: 0, status: "uploading", fileName: file.name });
    let progress = 0;
    if (uploadTimerRef.current) clearInterval(uploadTimerRef.current);
    uploadTimerRef.current = setInterval(() => {
      progress = Math.min(100, progress + Math.random() * 14 + 6);
      if (progress >= 100) {
        clearInterval(uploadTimerRef.current!);
        setUploadState(null);
        const newId = `m${Date.now()}`;
        const newMaterial: Material = {
          id: newId,
          name: file.name,
          status: "parsing",
          step: "parsing",
          progress: 20,
        };
        setMaterials((prev) => ({
          ...prev,
          [subject]: [newMaterial, ...prev[subject]],
        }));
        simulateParsing(newId, subject);
      } else {
        setUploadState((prev) => (prev ? { ...prev, progress: Math.floor(progress) } : prev));
      }
    }, 280);
  }

  /* ── Drag handlers ── */
  function handleDragEnter(e: React.DragEvent) {
    e.preventDefault();
    dragCounterRef.current++;
    setDragOver(true);
  }
  function handleDragLeave(e: React.DragEvent) {
    e.preventDefault();
    dragCounterRef.current--;
    if (dragCounterRef.current <= 0) {
      dragCounterRef.current = 0;
      setDragOver(false);
    }
  }
  function handleDragOver(e: React.DragEvent) {
    e.preventDefault();
  }
  function handleDrop(e: React.DragEvent) {
    e.preventDefault();
    dragCounterRef.current = 0;
    setDragOver(false);
    const file = e.dataTransfer.files[0];
    if (file) validateAndUpload(file);
  }

  function handleFileInput(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (file) validateAndUpload(file);
    e.target.value = "";
  }

  function handleRetry(id: string) {
    updateMaterial(id, subject, { status: "parsing", step: "parsing", progress: 20, error: undefined });
    simulateParsing(id, subject);
  }

  function handleMaterialClick(m: Material) {
    if (m.status !== "done") return;
    navigate(`/knowledge?materialId=${m.id}&subject=${subject}&name=${encodeURIComponent(m.name)}`);
  }

  return (
    <div
      className="min-h-screen bg-background flex flex-col"
      style={{ fontFamily: "'Noto Sans SC', 'Inter', sans-serif" }}
    >
      <Toaster position="top-center" richColors />

      {/* Header */}
      <header className="sticky top-0 z-30 bg-card border-b border-border h-14 flex items-center justify-between px-6">
        <span className="font-semibold text-foreground text-[0.9375rem]">费曼伴学</span>

        <div className="flex items-center gap-2">
          {/* Subject dropdown */}
        <div className="relative">
          <button
            onClick={() => setSubjectOpen((o) => !o)}
            onBlur={() => setTimeout(() => setSubjectOpen(false), 150)}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border bg-background text-[0.875rem] font-medium text-foreground hover:bg-muted transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          >
            {SUBJECT_LABELS[subject]}
            <ChevronDown
              size={14}
              strokeWidth={2}
              className={`transition-transform duration-150 ${subjectOpen ? "rotate-180" : ""}`}
            />
          </button>
          {subjectOpen && (
            <div className="absolute right-0 mt-1.5 w-28 bg-card border border-border rounded-xl shadow-lg overflow-hidden z-40">
              {(Object.keys(SUBJECT_LABELS) as Subject[]).map((s) => (
                <button
                  key={s}
                  onMouseDown={() => handleSubjectChange(s)}
                  className={`w-full text-left px-4 py-2.5 text-[0.875rem] transition-colors
                    ${s === subject
                      ? "bg-primary/8 text-primary font-semibold"
                      : "text-foreground hover:bg-muted"
                    }`}
                >
                  {SUBJECT_LABELS[s]}
                </button>
              ))}
            </div>
          )}
        </div>
          <UserMenu />
        </div>
      </header>

      <main className="flex-1 max-w-2xl w-full mx-auto px-4 py-8 flex flex-col gap-7">
        <h1 className="text-xl font-semibold text-foreground">上传教材PDF</h1>

        {/* Drop zone */}
        <div
          onDragEnter={handleDragEnter}
          onDragLeave={handleDragLeave}
          onDragOver={handleDragOver}
          onDrop={handleDrop}
          onClick={() => !isUploading && fileInputRef.current?.click()}
          className={`relative rounded-2xl border-2 border-dashed transition-all duration-200 flex flex-col items-center justify-center gap-4 min-h-[196px] select-none
            ${isUploading ? "pointer-events-none cursor-default" : "cursor-pointer"}
            ${dragOver
              ? "border-primary bg-blue-50 shadow-inner"
              : "border-border bg-card hover:border-primary/50 hover:bg-muted/30"
            }`}
        >
          <input
            ref={fileInputRef}
            type="file"
            accept=".pdf,application/pdf"
            className="hidden"
            onChange={handleFileInput}
          />

          {isUploading ? (
            <div className="flex flex-col items-center gap-3 px-10 w-full">
              <div className="w-12 h-12 rounded-2xl bg-primary/10 flex items-center justify-center">
                <FileText size={22} className="text-primary" strokeWidth={1.8} />
              </div>
              <div className="text-[0.875rem] text-muted-foreground truncate max-w-full px-4">
                {uploadState?.fileName}
              </div>
              <div className="w-full bg-muted rounded-full h-2 overflow-hidden">
                <div
                  className="h-2 bg-primary rounded-full transition-all duration-300 ease-out"
                  style={{ width: `${uploadState?.progress ?? 0}%` }}
                />
              </div>
              <div className="text-[0.9rem] text-primary font-semibold">
                文件上传中 {uploadState?.progress ?? 0}%
              </div>
            </div>
          ) : (
            <>
              <div
                className={`w-14 h-14 rounded-2xl flex items-center justify-center transition-all duration-200
                  ${dragOver ? "bg-primary/15 scale-110" : "bg-muted"}`}
              >
                <Upload
                  size={24}
                  className={`transition-colors ${dragOver ? "text-primary" : "text-muted-foreground"}`}
                  strokeWidth={1.8}
                />
              </div>
              <div className="text-center">
                <div className="text-[0.9375rem] font-medium text-foreground mb-1">
                  拖拽教材PDF到此处 / 点击选择文件
                </div>
                <div className="text-[0.8125rem] text-muted-foreground">
                  仅支持文字版PDF文件，文件大小上限50MB
                </div>
              </div>
            </>
          )}
        </div>

        {/* Upload error banner */}
        {uploadState?.status === "error" && (
          <div className="flex items-center justify-between px-4 py-3 rounded-xl bg-red-50 border border-red-200">
            <div className="flex items-center gap-2 text-red-700 text-[0.875rem]">
              <AlertCircle size={15} strokeWidth={2} className="flex-shrink-0" />
              {uploadState.errorMsg}
            </div>
            <button
              onClick={() => {
                setUploadState(null);
                fileInputRef.current?.click();
              }}
              className="ml-4 flex-shrink-0 text-[0.8125rem] font-semibold text-red-700 underline underline-offset-2 hover:text-red-900"
            >
              重新上传
            </button>
          </div>
        )}

        {/* Materials list */}
        <div className="flex flex-col gap-3">
          <div className="flex items-center justify-between">
            <h2 className="text-[0.8125rem] font-semibold text-muted-foreground uppercase tracking-wider">
              已上传教材 · {SUBJECT_LABELS[subject]}
            </h2>
            {currentMaterials.length > 0 && (
              <span className="text-[0.75rem] text-muted-foreground">{currentMaterials.length} 份</span>
            )}
          </div>

          {currentMaterials.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-14 gap-2">
              <div className="w-12 h-12 rounded-2xl bg-muted flex items-center justify-center mb-1">
                <FileText size={20} className="text-muted-foreground" strokeWidth={1.5} />
              </div>
              <p className="text-[0.9rem] text-muted-foreground text-center">
                暂无上传教材，请拖拽PDF文件上传
              </p>
            </div>
          ) : (
            <div className="flex flex-col gap-2">
              {currentMaterials.map((m) => (
                <MaterialItem
                  key={m.id}
                  material={m}
                  onClick={() => handleMaterialClick(m)}
                  onRetry={() => handleRetry(m.id)}
                />
              ))}
            </div>
          )}
        </div>
      </main>
    </div>
  );

  function handleSubjectChange(s: Subject) {
    setSubject(s);
    setSubjectOpen(false);
  }
}

// frontend/src/views/UploadPage.vue
<script setup>
import { ref, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { uploadMaterial, getMaterialStatus, getKnowledgeTree } from '@/api/feynman'

const router = useRouter()
const subjects = ['计算机', '数学', '政治']
const selectedSubject = ref('计算机')
const subjectOpen = ref(false)
const materials = ref([])
const isUploading = ref(false)
const uploadProgress = ref(0)
const uploadError = ref('')
const dropZoneActive = ref(false)
const fileInput = ref(null)
const dragCounterRef = ref(0)

const toastMessage = ref('')
const showToast = ref(false)

const STEP_LABELS = {
  parsing: '解析中',
  chunking: '分块中',
  extracting: '抽取中',
  generating: 'rubric生成中',
}

const pollingTimers = ref(new Map())

async function loadMaterials() {
  try {
    const tree = await getKnowledgeTree(selectedSubject.value)
    materials.value = tree.map(m => ({
      id: m.material_id,
      name: m.title + '.pdf',
      status: 'done',
      step: undefined,
      progress: undefined,
      error: null
    }))
    
    const generatingMat = { 
      id: 'mat-generating', 
      name: '数据结构教材.pdf', 
      status: 'generating', 
      step: 'generating', 
      progress: 60, 
      error: null 
    }
    const idx = materials.value.findIndex(m => m.id === 'mat-generating')
    if (idx >= 0) {
      materials.value[idx] = generatingMat
    } else {
      materials.value.unshift(generatingMat)
    }
    
    materials.value.forEach(m => {
      if (['parsing', 'chunking', 'extracting', 'generating'].includes(m.status)) {
        startStatusPolling(m.id)
      }
    })
  } catch (e) {
    showToastMsg(e.message)
  }
}

function handleDrop(e) {
  e.preventDefault()
  dragCounterRef.value = 0
  dropZoneActive.value = false
  const file = e.dataTransfer.files[0]
  if (file) validateAndUpload(file)
}

function handleDragEnter(e) {
  e.preventDefault()
  dragCounterRef.value++
  dropZoneActive.value = true
}

function handleDragLeave(e) {
  e.preventDefault()
  dragCounterRef.value--
  if (dragCounterRef.value <= 0) {
    dragCounterRef.value = 0
    dropZoneActive.value = false
  }
}

function handleDragOver(e) {
  e.preventDefault()
}

function handleClickDropZone() {
  if (!isUploading.value) {
    fileInput.value?.click()
  }
}

function handleFileInputChange(e) {
  const file = e.target.files?.[0]
  if (file) validateAndUpload(file)
  e.target.value = ''
}

function validateAndUpload(file) {
  if (isUploading.value) return
  const isPdf = file.name.toLowerCase().endsWith('.pdf') && file.type === 'application/pdf'
  if (!isPdf) {
    showToastMsg('仅支持文字版PDF文件')
    return
  }
  if (file.size > 50 * 1024 * 1024) {
    uploadError.value = '文件超过50MB大小限制'
    return
  }
  startUpload(file)
}

async function startUpload(file) {
  isUploading.value = true
  uploadProgress.value = 0
  uploadError.value = ''
  
  try {
    const result = await uploadMaterial(file, selectedSubject.value, (percent) => {
      uploadProgress.value = percent
    })
    
    isUploading.value = false
    
    const newMaterial = {
      id: result.material_id,
      name: file.name,
      status: result.status || 'parsing',
      step: result.step || 'parsing',
      progress: (result.progress || 0) * 100,
      error: null
    }
    materials.value.unshift(newMaterial)
    startStatusPolling(newMaterial.id)
  } catch (e) {
    isUploading.value = false
    uploadError.value = e.message || '上传失败，请重试'
  }
}

function startStatusPolling(materialId) {
  if (pollingTimers.value.has(materialId)) {
    clearInterval(pollingTimers.value.get(materialId))
  }
  
  const timer = setInterval(async () => {
    try {
      const status = await getMaterialStatus(materialId)
      updateMaterial(materialId, {
        status: status.status,
        step: status.step,
        progress: status.progress ? status.progress * 100 : undefined,
        error: status.error || null
      })
      
      if (status.status === 'done' || status.status === 'failed') {
        stopStatusPolling(materialId)
      }
    } catch (e) {
      stopStatusPolling(materialId)
    }
  }, 2000)
  
  pollingTimers.value.set(materialId, timer)
}

function stopStatusPolling(materialId) {
  const timer = pollingTimers.value.get(materialId)
  if (timer) {
    clearInterval(timer)
    pollingTimers.value.delete(materialId)
  }
}

function updateMaterial(id, patch) {
  materials.value = materials.value.map(m => m.id === id ? { ...m, ...patch } : m)
}

function handleRetry(id) {
  updateMaterial(id, { status: 'parsing', step: 'parsing', progress: 0, error: undefined })
  startStatusPolling(id)
}

function handleMaterialClick(m) {
  if (m.status !== 'done') return
  router.push(`/knowledge?materialId=${m.id}&subject=${selectedSubject.value}&name=${encodeURIComponent(m.name)}`)
}

function showToastMsg(msg) {
  toastMessage.value = msg
  showToast.value = true
  setTimeout(() => {
    showToast.value = false
  }, 3000)
}

function handleSubjectChange(s) {
  selectedSubject.value = s
  subjectOpen.value = false
  pollingTimers.value.forEach(timer => clearInterval(timer))
  pollingTimers.value.clear()
  loadMaterials()
}

onMounted(() => {
  loadMaterials()
})

watch(selectedSubject, () => {
  pollingTimers.value.forEach(timer => clearInterval(timer))
  pollingTimers.value.clear()
  loadMaterials()
})
</script>

<template>
  <div class="upload-page">
    <header class="upload-header">
      <span class="page-title">费曼伴学</span>
      
      <div class="subject-dropdown">
        <button
          class="subject-btn"
          @click="subjectOpen = !subjectOpen"
          @blur="setTimeout(() => subjectOpen = false, 150)"
        >
          {{ selectedSubject }}
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" :class="{ 'rotate-180': subjectOpen }">
            <polyline points="6 9 12 15 18 9" />
          </svg>
        </button>
        <div v-if="subjectOpen" class="subject-menu">
          <button
            v-for="s in subjects"
            :key="s"
            class="subject-item"
            :class="{ 'subject-item--selected': s === selectedSubject }"
            @click="handleSubjectChange(s)"
          >
            {{ s }}
          </button>
        </div>
      </div>
    </header>

    <main class="upload-main">
      <h1 class="main-title">上传教材PDF</h1>

      <div
        class="drop-zone"
        :class="{ 'drop-zone--active': dropZoneActive, 'drop-zone--uploading': isUploading }"
        @drop="handleDrop"
        @dragenter="handleDragEnter"
        @dragleave="handleDragLeave"
        @dragover="handleDragOver"
        @click="handleClickDropZone"
      >
        <input
          ref="fileInput"
          type="file"
          accept=".pdf,application/pdf"
          class="file-input"
          @change="handleFileInputChange"
        />

        <template v-if="isUploading">
          <div class="uploading-content">
            <div class="upload-icon-wrapper">
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                <polyline points="14 2 14 8 20 8" />
                <line x1="16" y1="13" x2="8" y2="13" />
                <line x1="16" y1="17" x2="8" y2="17" />
                <polyline points="10 9 9 9 8 9" />
              </svg>
            </div>
            <div class="upload-filename">{{ uploadProgress > 0 ? '正在上传...' : '' }}</div>
            <div class="upload-progress-bar">
              <div class="progress-fill" :style="{ width: uploadProgress + '%' }"></div>
            </div>
            <div class="upload-percent">文件上传中 {{ uploadProgress }}%</div>
          </div>
        </template>

        <template v-else>
          <div class="drop-icon-wrapper" :class="{ 'drop-icon-wrapper--active': dropZoneActive }">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" :class="{ 'drop-icon--active': dropZoneActive }">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
              <polyline points="17 8 12 3 7 8" />
              <line x1="12" y1="3" x2="12" y2="15" />
            </svg>
          </div>
          <div class="drop-text">拖拽教材PDF到此处 / 点击选择文件</div>
          <div class="drop-hint">仅支持文字版PDF文件，文件大小上限50MB</div>
        </template>
      </div>

      <div v-if="uploadError" class="upload-error">
        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <circle cx="12" cy="12" r="10" />
          <line x1="12" y1="8" x2="12" y2="12" />
          <line x1="12" y1="16" x2="12.01" y2="16" />
        </svg>
        {{ uploadError }}
        <button class="retry-link" @click="fileInput?.click()">重新上传</button>
      </div>

      <div class="materials-section">
        <div class="section-header">
          <h2 class="section-title">已上传教材 · {{ selectedSubject }}</h2>
          <span v-if="materials.length > 0" class="section-count">{{ materials.length }} 份</span>
        </div>

        <div v-if="materials.length === 0" class="empty-state">
          <div class="empty-icon">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
              <polyline points="14 2 14 8 20 8" />
              <line x1="16" y1="13" x2="8" y2="13" />
              <line x1="16" y1="17" x2="8" y2="17" />
              <polyline points="10 9 9 9 8 9" />
            </svg>
          </div>
          <p>暂无上传教材，请拖拽PDF文件上传</p>
        </div>

        <div v-else class="material-list">
          <div
            v-for="m in materials"
            :key="m.id"
            class="material-item"
            :class="{
              'material-item--done': m.status === 'done',
              'material-item--failed': m.status === 'failed',
              'material-item--processing': ['parsing', 'chunking', 'extracting', 'generating'].includes(m.status)
            }"
            @click="handleMaterialClick(m)"
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" :class="{ 'material-icon--done': m.status === 'done' }">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
              <polyline points="14 2 14 8 20 8" />
              <line x1="16" y1="13" x2="8" y2="13" />
              <line x1="16" y1="17" x2="8" y2="17" />
              <polyline points="10 9 9 9 8 9" />
            </svg>

            <div class="material-info">
              <div class="material-name">{{ m.name }}</div>
              
              <template v-if="['parsing', 'chunking', 'extracting', 'generating'].includes(m.status)">
                <div class="processing-info">
                  <span class="processing-text">{{ STEP_LABELS[m.step] || m.step }}</span>
                  <span class="processing-percent">{{ m.progress }}%</span>
                </div>
                <div class="processing-bar">
                  <div class="bar-fill" :style="{ width: m.progress + '%' }"></div>
                </div>
              </template>

              <template v-else-if="m.status === 'done'">
                <div class="done-info">
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
                    <polyline points="20 6 9 17 4 12" />
                  </svg>
                  <span>已完成 · 点击查看知识点</span>
                </div>
              </template>

              <template v-else-if="m.status === 'failed'">
                <div class="failed-info">
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <circle cx="12" cy="12" r="10" />
                    <line x1="12" y1="8" x2="12" y2="12" />
                    <line x1="12" y1="16" x2="12.01" y2="16" />
                  </svg>
                  <span>{{ m.error || '解析失败' }}</span>
                </div>
              </template>
            </div>

            <svg v-if="['parsing', 'chunking', 'extracting', 'generating'].includes(m.status)" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="spinner">
              <circle cx="12" cy="12" r="10" stroke-linecap="round" stroke-dasharray="16 16" />
            </svg>

            <button
              v-if="m.status === 'failed'"
              class="retry-btn"
              @click.stop="handleRetry(m.id)"
            >
              重试解析
            </button>
          </div>
        </div>
      </div>
    </main>

    <div v-if="showToast" class="toast">{{ toastMessage }}</div>
  </div>
</template>

<style scoped>
.upload-page {
  min-height: 100vh;
  background: #F8FAFC;
  display: flex;
  flex-direction: column;
  font-family: 'Noto Sans SC', 'Inter', sans-serif;
}

.upload-header {
  position: sticky;
  top: 0;
  z-index: 30;
  background: #FFFFFF;
  border-bottom: 1px solid #E2E8F0;
  height: 56px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 24px;
}

.page-title {
  font-size: 15px;
  font-weight: 600;
  color: #1E293B;
}

.subject-dropdown {
  position: relative;
}

.subject-btn {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 12px;
  border-radius: 8px;
  border: 1px solid #E2E8F0;
  background: #FFFFFF;
  font-size: 14px;
  font-weight: 500;
  color: #1E293B;
  transition: all 150ms;
}

.subject-btn:hover {
  background: #F1F5F9;
}

.subject-menu {
  position: absolute;
  right: 0;
  top: calc(100% + 6px);
  width: 112px;
  background: #FFFFFF;
  border: 1px solid #E2E8F0;
  border-radius: 12px;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);
  overflow: hidden;
  z-index: 40;
}

.subject-item {
  width: 100%;
  text-align: left;
  padding: 10px 16px;
  font-size: 14px;
  color: #1E293B;
  transition: all 150ms;
}

.subject-item:hover:not(.subject-item--selected) {
  background: #F1F5F9;
}

.subject-item--selected {
  background: rgba(37, 99, 235, 0.08);
  color: #2563EB;
  font-weight: 600;
}

.upload-main {
  flex: 1;
  padding: 32px 16px;
  max-width: 800px;
  margin: 0 auto;
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 28px;
}

.main-title {
  font-size: 20px;
  font-weight: 600;
  color: #1E293B;
  margin: 0;
}

.drop-zone {
  border: 2px dashed #CBD5E1;
  border-radius: 16px;
  padding: 48px;
  text-align: center;
  cursor: pointer;
  transition: all 200ms;
  background: #FFFFFF;
  min-height: 196px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.drop-zone:hover:not(.drop-zone--uploading) {
  border-color: rgba(37, 99, 235, 0.5);
  background: rgba(37, 99, 235, 0.02);
}

.drop-zone--active {
  border-color: #2563EB;
  background: rgba(37, 99, 235, 0.04);
}

.drop-zone--uploading {
  pointer-events: none;
}

.file-input {
  display: none;
}

.drop-icon-wrapper {
  width: 56px;
  height: 56px;
  border-radius: 16px;
  background: #F1F5F9;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 16px;
  transition: all 200ms;
}

.drop-icon-wrapper--active {
  background: rgba(37, 99, 235, 0.15);
  transform: scale(1.1);
}

.drop-icon {
  color: #94A3B8;
}

.drop-icon--active {
  color: #2563EB;
}

.drop-text {
  font-size: 15px;
  font-weight: 500;
  color: #1E293B;
  margin-bottom: 8px;
}

.drop-hint {
  font-size: 13px;
  color: #64748B;
}

.uploading-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
  width: 100%;
}

.upload-icon-wrapper {
  width: 48px;
  height: 48px;
  border-radius: 12px;
  background: rgba(37, 99, 235, 0.1);
  display: flex;
  align-items: center;
  justify-content: center;
  color: #2563EB;
}

.upload-filename {
  font-size: 14px;
  color: #64748B;
  max-width: 100%;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.upload-progress-bar {
  width: 100%;
  height: 8px;
  background: #E2E8F0;
  border-radius: 4px;
  overflow: hidden;
}

.progress-fill {
  height: 100%;
  background: #2563EB;
  transition: width 300ms ease-out;
}

.upload-percent {
  font-size: 14px;
  font-weight: 600;
  color: #2563EB;
}

.upload-error {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  border-radius: 12px;
  background: rgba(239, 68, 68, 0.06);
  border: 1px solid rgba(239, 68, 68, 0.15);
  color: #DC2626;
  font-size: 14px;
}

.retry-link {
  font-size: 13px;
  font-weight: 600;
  color: #DC2626;
  text-decoration: underline;
  text-underline-offset: 4px;
}

.materials-section {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.section-title {
  font-size: 13px;
  font-weight: 600;
  color: #64748B;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  margin: 0;
}

.section-count {
  font-size: 12px;
  color: #94A3B8;
}

.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  padding: 56px;
}

.empty-icon {
  width: 48px;
  height: 48px;
  border-radius: 16px;
  background: #F1F5F9;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #94A3B8;
}

.empty-state p {
  margin: 0;
  font-size: 14px;
  color: #94A3B8;
}

.material-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.material-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 14px 16px;
  background: #FFFFFF;
  border: 1px solid #E2E8F0;
  border-radius: 12px;
  transition: all 150ms;
}

.material-item--done {
  cursor: pointer;
}

.material-item--done:hover {
  border-color: rgba(37, 99, 235, 0.4);
  background: rgba(37, 99, 235, 0.02);
}

.material-icon--done {
  color: rgba(37, 99, 235, 0.6);
}

.material-info {
  flex: 1;
  min-width: 0;
}

.material-name {
  font-size: 14px;
  font-weight: 500;
  color: #1E293B;
  margin-bottom: 4px;
}

.processing-info {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 6px;
}

.processing-text {
  font-size: 13px;
  color: #64748B;
}

.processing-percent {
  font-size: 13px;
  color: #2563EB;
  font-weight: 500;
}

.processing-bar {
  height: 6px;
  background: #E2E8F0;
  border-radius: 3px;
  overflow: hidden;
}

.bar-fill {
  height: 100%;
  background: #2563EB;
  transition: width 700ms;
}

.done-info {
  display: flex;
  align-items: center;
  gap: 6px;
  color: #10B981;
  font-size: 13px;
  font-weight: 500;
}

.failed-info {
  display: flex;
  align-items: center;
  gap: 6px;
  color: #EF4444;
  font-size: 13px;
}

.spinner {
  animation: spin 1s linear infinite;
  color: #2563EB;
}

@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.retry-btn {
  padding: 6px 12px;
  border: 1px solid rgba(37, 99, 235, 0.3);
  border-radius: 8px;
  font-size: 13px;
  font-weight: 600;
  color: #2563EB;
  transition: all 150ms;
}

.retry-btn:hover {
  background: rgba(37, 99, 235, 0.05);
}

.toast {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  padding: 12px 24px;
  background: rgba(15, 23, 42, 0.9);
  color: #FFFFFF;
  border-radius: 10px;
  font-size: 14px;
  z-index: 200;
}

.rotate-180 {
  transform: rotate(180deg);
}
</style>
